# Generated by Django 5.2.6 on 2025-10-06 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Darslik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('file', models.FileField(upload_to='darsliklar')),
                ('sinf', models.PositiveSmallIntegerField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('changed_date', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appv1.fan')),
            ],
        ),
    ]
