# Generated by Django 5.2.6 on 2025-10-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0002_darslik'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='korishlar_soni',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
