# Generated by Django 5.2.6 on 2025-10-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0003_presentation_korishlar_soni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='darslik',
            name='sinf',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='sinf',
        ),
        migrations.AddField(
            model_name='fan',
            name='sinf',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
