# Generated by Django 5.2.6 on 2025-10-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0004_remove_darslik_sinf_remove_presentation_sinf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='sinf',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
