# Generated by Django 5.2.6 on 2025-11-19 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0005_alter_fan_sinf'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='guruh',
            field=models.CharField(choices=[("o'zbek", "o'zbek"), ('rus', 'rus')], default="o'zbek", max_length=10),
        ),
        migrations.AddField(
            model_name='presentation',
            name='chorak',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='IshReja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ish_rejalar')),
                ('chorak', models.PositiveSmallIntegerField(default=1)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('changed_date', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appv1.fan')),
            ],
        ),
    ]
