# Generated by Django 5.2.6 on 2025-11-22 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appv1', '0006_fan_guruh_presentation_chorak_ishreja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='fan',
        ),
        migrations.AddField(
            model_name='darslik',
            name='yil',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='darslik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appv1.darslik'),
        ),
    ]
